// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIISZRhjsvdFzK7K5l9axfaJAEpjZyeOg',
    appId: '1:318595525356:web:6097473cc61552ff1313c9',
    messagingSenderId: '318595525356',
    projectId: 'workout-logger-vk69',
    authDomain: 'workout-logger-vk69.firebaseapp.com',
    storageBucket: 'workout-logger-vk69.firebasestorage.app',
    measurementId: 'G-R2ZW11DQT7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDeRSgLC2wXUw_8ZTALa_a1_jsQk9MImdY',
    appId: '1:318595525356:android:fe0031bb8b48108c1313c9',
    messagingSenderId: '318595525356',
    projectId: 'workout-logger-vk69',
    storageBucket: 'workout-logger-vk69.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZu_k-6Bpjs11XhSRf_Av1GDeU4Cl2vzg',
    appId: '1:318595525356:ios:05858071fbd034bf1313c9',
    messagingSenderId: '318595525356',
    projectId: 'workout-logger-vk69',
    storageBucket: 'workout-logger-vk69.firebasestorage.app',
    iosBundleId: 'com.example.workoutLogger',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZu_k-6Bpjs11XhSRf_Av1GDeU4Cl2vzg',
    appId: '1:318595525356:ios:05858071fbd034bf1313c9',
    messagingSenderId: '318595525356',
    projectId: 'workout-logger-vk69',
    storageBucket: 'workout-logger-vk69.firebasestorage.app',
    iosBundleId: 'com.example.workoutLogger',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBIISZRhjsvdFzK7K5l9axfaJAEpjZyeOg',
    appId: '1:318595525356:web:81d618ac2eec34921313c9',
    messagingSenderId: '318595525356',
    projectId: 'workout-logger-vk69',
    authDomain: 'workout-logger-vk69.firebaseapp.com',
    storageBucket: 'workout-logger-vk69.firebasestorage.app',
    measurementId: 'G-HQD6HMPR0J',
  );
}
